---
apiVersion: v1
kind: Template
metadata:
  name: ${APP}-${COMPONENT}
labels:
  app: ${APP}
  component: ${COMPONENT}
parameters:
  - name: APP
    value: baserow
  - name: COMPONENT
    value: backend
  - name: BUILD_TAG
    value: "1.2.0"
  - name: IMG_SRC_TAG
    value: "3.8"
  - name: IMG_SRC_NAME
    value: python
  - name: IMG_SRC_NAMESPACE
    value: openshift
  - name: IMG_SRC_REPO
    value: image-registry.openshift-image-registry.svc:5000
  - name: DEPLOY_NAMESPACE
    value: 245e18-dev
  - name: DOMAIN
    value: apps.silver.devops.gov.bc.ca
  - name: CLONE_GIT_RELEASE
    value: "1.2.0"
  - name: CLONE_GIT_URL
    value: https://gitlab.com/bramw/baserow.git
objects:
  - apiVersion: v1
    kind: ImageStream
    metadata:
      labels:
        app: ${APP}
        component: ${COMPONENT}
      name: ${APP}-${COMPONENT}
  - apiVersion: v1
    kind: BuildConfig
    metadata:
      labels:
        app: ${APP}
        component: ${COMPONENT}
      name: ${APP}-${COMPONENT}
    spec:
      output:
        to:
          kind: ImageStreamTag
          name: ${APP}-${COMPONENT}:${BUILD_TAG}
      source:
        dockerfile: |
          FROM ${IMG_SRC_REPO}/${IMG_SRC_NAMESPACE}/${IMG_SRC_NAME}:${IMG_SRC_TAG}

          ENV PYTHONPATH $PYTHONPATH/backend/src
          ENV DJANGO_SETTINGS_MODULE='baserow.config.settings.dev'

          USER root
          RUN yum install -y gnupg2 postgresql postgresql-contrib postgresql-libs

          WORKDIR /backend
          RUN git clone ${CLONE_GIT_URL} -b ${CLONE_GIT_RELEASE} /tmp/baserow && \
              cp -rT /tmp/baserow/backend . && \
              rm -rf /tmp/baserow
          RUN pip3 install -r ./requirements/base.txt

          # Bug - URLs not automatically being added to ALLOWED_HOSTS
          ENV ALLOWED_HOSTS_FIX=${APP}-${COMPONENT}-${DEPLOY_NAMESPACE}.${DOMAIN}
          RUN sed -i "/^ALLOWED_HOSTS =.*/a ALLOWED_HOSTS.append(\'${ALLOWED_HOSTS_FIX}\')" \
                src/baserow/config/settings/base.py
          CMD gunicorn --workers=3 -b 0.0.0.0:8000 baserow.config.wsgi

        type: Dockerfile
      strategy:
        type: Docker
      triggers:
        - type: ConfigChange
        - imageChange: {}
          type: ImageChange
