---
apiVersion: v1
kind: Template
labels:
  app: ${APP}
  component: ${COMPONENT}
parameters:
  - name: APP
    value: baserow
  - name: COMPONENT
    value: web-frontend
  - name: IMG_IS_TAG
    value: latest
  - name: IMG_SRC_TAG
    value: latest
  - name: SRC_GIT_URL
    value: https://gitlab.com/bramw/baserow.git
  - name: SRC_RELEASE
    value: 0.7.1
objects:
  - apiVersion: v1
    kind: ImageStream
    metadata:
      labels:
        app: ${APP}
        component: ${COMPONENT}
      name: ${APP}-${COMPONENT}
  - apiVersion: v1
    kind: BuildConfig
    metadata:
      labels:
        app: ${APP}
        component: ${COMPONENT}
      name: ${APP}-${COMPONENT}
    spec:
      output:
        to:
          kind: ImageStreamTag
          name: ${APP}-${COMPONENT}:${IMG_IS_TAG}
      resources:
        limits:
          memory: 4Gi
        requests:
          memory: 2Gi
      selector:
        app: ${APP}-${COMPONENT}
        component: ${COMPONENT}
      source:
        dockerfile: |
          FROM image-registry.openshift-image-registry.svc:5000/openshift/nodejs:10

          USER root
          WORKDIR /web-frontend

          RUN git clone ${SRC_GIT_URL} -b ${SRC_RELEASE} /tmp/baserow && \
              cp -rT /tmp/baserow/web-frontend . && \
              rm -rf /tmp/baserow

          RUN mkdir /.npm && \
              chown -R 1000870000:0 /.npm && \
              chmod -R 777 /web-frontend

          RUN sed 's/"nuxt": "2.12.1",/"nuxt": "2.15.2",/' package.json > package.json.updated && \
              mv package.json.updated package.json

          RUN npm install --unsafe-perm=true --allow-root

          RUN npm run build

          CMD npm run start

        type: Dockerfile
      strategy:
        type: Docker
      triggers:
        - type: ConfigChange
        - imageChange: {}
          type: ImageChange
